export const SET_ANGLE = "SET_ANGLE";
export const SET_ACTIVE_CHARACTER = "SET_ACTIVE_CHARACTER";
export const ADD_CHARACTER = "ADD_CHARACTER";
export const REMOVE_ACTIVE_CHARACTER = "REMOVE_ACTIVE_CHARACTER";
